# =============================================================================
# app/schemas.py
# -----------------------------------------------------------------------------
# Pydantic models define the SHAPE of data going in and out of the API.
# FastAPI uses these to: validate incoming JSON automatically (rejecting
# malformed requests with a 422 before your route code even runs), and to
# serialize outgoing responses consistently.
#
# NOTE: this file merges the two halves of app/schemas.py you've shown me
# (Campaign/webhook models + BusinessMemoryBox/insights models — they're the
# same file, since insights_engine.py's `.schemas` import and main.py's
# `app.schemas` import both resolve here). ONE addition on top of what you
# already have: `contact_email` on BusinessMemoryBox, so the DM auto-reply
# has somewhere to point a customer when it can't find the answer.
# =============================================================================
from __future__ import annotations
from datetime import datetime
from typing import Optional, Literal
from uuid import UUID

from pydantic import BaseModel, Field, HttpUrl


# ---------------------------------------------------------------------------
# CAMPAIGNS / WEBHOOK — unchanged from what you already have
# ---------------------------------------------------------------------------

class CampaignCreate(BaseModel):
    """Shape of the JSON body expected on POST /api/campaigns."""

    trigger_word: str = Field(..., min_length=1, max_length=100)
    destination_link: HttpUrl
    message_template: str | None = Field(default=None, max_length=1000)

    class Config:
        json_schema_extra = {
            "example": {
                "trigger_word": "PRICE",
                "destination_link": "https://yourshop.com/pricing",
                "message_template": "Hey! Here's our pricing page 👇",
            }
        }


class CampaignUpdate(BaseModel):
    """
    Shape of the JSON body expected on PATCH /api/campaigns/{id}. Every
    field is optional — the frontend sends only what actually changed,
    and the endpoint only updates keys that were provided.
    """

    trigger_word: str | None = Field(default=None, min_length=1, max_length=100)
    destination_link: HttpUrl | None = None
    message_template: str | None = Field(default=None, max_length=1000)
    is_active: bool | None = None


class CampaignOut(BaseModel):
    """Shape of a campaign object as returned to the client."""

    id: UUID
    trigger_word: str
    destination_link: str
    message_template: str | None = None
    is_active: bool
    created_at: datetime


class InstagramWebhookPayload(BaseModel):
    """
    Simulates the payload Instagram's real webhook would send when someone
    comments on a post. A real integration would verify Meta's signature
    header here too (X-Hub-Signature-256) — omitted since this endpoint is
    explicitly a simulation per the assignment, but noted in the README.
    """

    commenter_username: str = Field(..., min_length=1)
    comment_text: str = Field(..., min_length=1)
    recipient_account_id: str = Field(..., min_length=1)
    commenter_igsid: str | None = None


class WebhookResult(BaseModel):
    status: str
    matched_trigger: str | None = None
    dm_sent_to: str | None = None
    dms_sent_count: int | None = None
    dm_delivery: str | None = None


class ActivityEvent(BaseModel):
    id: UUID
    trigger_word: str
    commenter_username: str
    sent_at: datetime


class DailyTrendPoint(BaseModel):
    date: str
    count: int


class AnalyticsOut(BaseModel):
    dms_sent_count: int
    free_tier_limit: int
    daily_trend: list[DailyTrendPoint]
    recent_activity: list[ActivityEvent]


# ---------------------------------------------------------------------------
# BUSINESS MEMORY BOX — owner-provided facts only. Nothing in here is ever
# generated by the AI. This is the single grounding source for every prompt
# (used by both insights_engine.py and the DM auto-reply engine).
# ---------------------------------------------------------------------------

class Product(BaseModel):
    name: str
    description: Optional[str] = None
    price: Optional[str] = None            # kept as string: "$25", "₹499-999", "Contact for quote"
    category: Optional[str] = None
    is_best_seller: bool = False
    wants_to_sell_more: bool = False


class FAQ(BaseModel):
    question: str
    answer: str


class BusinessMemoryBox(BaseModel):
    business_id: str
    business_name: str

    products: list[Product] = Field(default_factory=list)
    services: list[Product] = Field(default_factory=list)

    target_customers: Optional[str] = None
    brand_voice: Optional[str] = None

    offers: list[str] = Field(default_factory=list)
    discounts: list[str] = Field(default_factory=list)
    promotions: list[str] = Field(default_factory=list)

    faqs: list[FAQ] = Field(default_factory=list)
    shipping_policy: Optional[str] = None
    return_policy: Optional[str] = None

    competitors: list[str] = Field(default_factory=list)
    goals: list[str] = Field(default_factory=list)

    customer_pain_points: list[str] = Field(default_factory=list)
    common_questions: list[str] = Field(default_factory=list)
    keywords: list[str] = Field(default_factory=list)

    business_rules: list[str] = Field(
        default_factory=list,
        description="Hard constraints the AI must always respect, e.g. "
                    "'Never promise same-day delivery', 'Never discuss competitor pricing'.",
    )

    # NEW — where to point a customer when the AI can't ground an answer
    # in a DM reply. Optional, defaults to None, no migration needed since
    # this whole box is stored as jsonb (see sql/003_memory_box_and_insights.sql).
    contact_email: Optional[str] = None

    updated_at: datetime = Field(default_factory=datetime.utcnow)


class BusinessMemoryBoxUpdate(BaseModel):
    """Partial update payload — any subset of BusinessMemoryBox fields except business_id."""
    business_name: Optional[str] = None
    products: Optional[list[Product]] = None
    services: Optional[list[Product]] = None
    target_customers: Optional[str] = None
    brand_voice: Optional[str] = None
    offers: Optional[list[str]] = None
    discounts: Optional[list[str]] = None
    promotions: Optional[list[str]] = None
    faqs: Optional[list[FAQ]] = None
    shipping_policy: Optional[str] = None
    return_policy: Optional[str] = None
    competitors: Optional[list[str]] = None
    goals: Optional[list[str]] = None
    customer_pain_points: Optional[list[str]] = None
    common_questions: Optional[list[str]] = None
    keywords: Optional[list[str]] = None
    business_rules: Optional[list[str]] = None
    contact_email: Optional[str] = None


class MemoryMessageRequest(BaseModel):
    """A free-text note the owner types into the memory box, e.g.
    'Our return window is 30 days and the Vitamin C Serum is $25.'"""
    text: str = Field(min_length=1, max_length=4000)


class MemoryMessageResponse(BaseModel):
    memory_box: BusinessMemoryBox
    extracted_fields: dict = Field(
        default_factory=dict,
        description="Only the fields that changed as a result of this message, "
                    "for the UI to highlight what was just learned.",
    )
    model_used: str
    raw_note: str


# ---------------------------------------------------------------------------
# CONVERSATION DATA — raw DM/comment input for a given analysis run
# ---------------------------------------------------------------------------

class Message(BaseModel):
    role: Literal["customer", "business"]
    text: str
    timestamp: Optional[datetime] = None


class Conversation(BaseModel):
    customer_id: str
    source: Literal["dm", "comment"] = "dm"
    messages: list[Message]


class AnalyzeRequest(BaseModel):
    conversations: list[Conversation]


# ---------------------------------------------------------------------------
# INSIGHT OUTPUT — everything below is AI-GENERATED.
# ---------------------------------------------------------------------------

class ProductMentionStat(BaseModel):
    product_name: str
    mention_count: int
    source: Literal["computed"] = "computed"


class CustomerIntent(BaseModel):
    customer_id: str
    intent: Literal["hot", "warm", "cold"]
    lead_score: int = Field(ge=0, le=100)
    reasoning: str


class InsightsResult(BaseModel):
    business_id: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    model_used: str

    computed_product_mentions: list[ProductMentionStat] = Field(default_factory=list)

    summary: str
    sentiment_overview: str
    customer_intents: list[CustomerIntent] = Field(default_factory=list)
    common_questions: list[str] = Field(default_factory=list)
    objections: list[str] = Field(default_factory=list)
    why_customers_arent_buying: list[str] = Field(default_factory=list)
    what_customers_want: list[str] = Field(default_factory=list)
    trending_topics: list[str] = Field(default_factory=list)
    sales_opportunities: list[str] = Field(default_factory=list)
    recommended_actions: list[str] = Field(default_factory=list)
    product_opportunities: list[str] = Field(default_factory=list)

    class Config:
        json_schema_extra = {
            "description": "All fields except computed_product_mentions are AI-generated "
                            "and must be grounded strictly in the BusinessMemoryBox + supplied "
                            "conversations. Nothing here is a stored business fact."
        }